version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Kevin
      POSTGRES_PASSWORD: Dino
      POSTGRES_DB: your_postgres_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: faller2510@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: Dino
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
